handler: src/account/index.handler
runtime: nodejs16.x
name: Paya-IVR-account-${self:provider.stage}
iamRoleStatementsName: Paya-IVR-account-${self:provider.stage}-role
memorySize: 128
timeout: 30
package:
  include: 
    - 'account/node_modules/**'
  patterns: 
    - 'account/**'
    - 'account/node_modules/**'
    - '!node_modules/**'
events:
  - http: 
      method: GET
      path: account/{accountNumber}
      integration: lambda
      # authorizer:
      #     name: authorizer
      #     resultTtlInSeconds: 0
      #     identitySource: method.request.header.Authorization
      #     type: token
      response:
        headers:
          Content-Type: "'application/json'"
        template: $input.path("$.body")
        statusCodes:
          200:
            pattern: '' # Default response method
            template:
              # Your script returns json, so match it here
              application/json: $input.path("$.body")
            headers:
              Content-Type: "'application/json'"
environment:
  NODE_ENV: ${self:provider.stage}
  NODE_API_KEY: ${env:NODE_API_KEY, "123123123"} 
  NODE_API_PASS: ${env:NODE_API_PASS, "123123123"} 
  # JWT setting
  JWT_SECRET: ${env:JWT_SECRET, "secretKey"} 
  JWT_TOKEN_EXPIRY_IN_MINS: ${env:JWT_TOKEN_EXPIRY_IN_MINS, "15"}
  # This below env variables for MB ROR API access
  MB_BILLING_PAYA_API_HOST: ${env:MB_BILLING_PAYA_API_HOST, "https://connect.staging.munibilling.com:443/api"}
  MB_BILLING_PAYA_API_NAMESPACE: ${env:MB_BILLING_PAYA_API_NAMESPACE, "v1"}
  MB_BILLING_PAYA_API_LIFE_TOKEN: ${env:MB_BILLING_PAYA_API_LIFE_TOKEN, "LkI1PKm0SAtdzyTssn622JoI08Tc5NpX0"}
  # This below env variables for MB NODE paya adapter API access
  MB_NODE_PAYA_API_HOST: ${env:MB_NODE_PAYA_API_HOST, "http://localhost:5431/api/service"}
  MB_NODE_PAYA_API_NAMESPACE: ${env:MB_NODE_PAYA_API_NAMESPACE, "v1"}
  MB_NODE_PAYA_API_LIFE_TOKEN: ${env:MB_NODE_PAYA_API_LIFE_TOKEN, "LkI1PKm0SAtdzyTssn622JoI08Tc5NpX0"}